# Coding Assignment - 4

#### Authors:
+ Yogananth Mahalingam - ym24 - MCS-DS
+ Qi Zhou - qizhou8 - MCS-DS
+ Derek Zhang - derekz3 - MCS-DS

#### Contributions:
Yoga, Derek & Qi worked on it independently. Brainstormed together & created the final version.

## Part 2: HMM

In [77]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from matplotlib.colors import LogNorm



In [78]:
itmax = 100

mx = 3
mz = 2
w = np.array([0.5, 0.5])
A = np.array([[0.5, 0.5], 
              [0.5, 0.5]])
B = np.array([[1/9, 3/9, 5/9], 
              [1/6, 2/6, 3/6]])

X = np.loadtxt("coding4_part2_data.txt").astype(int)

Z_test = np.genfromtxt("Coding4_part2_Z.txt").astype(int)


In [79]:
def BW_onstep(X, mx, mz, w, A, B):
    new_w = w
    new_A = A
    new_B = B
    
    alpha = calculate_alpha(X, mx, mz, w, new_A, new_B)
    beta = calculate_beta(X, mx, mz, w, new_A, new_B)
    gamma = calculate_gamma(X, mx, mz, w, A, B, alpha, beta)
    
    new_w = update_w(X, mx, mz, w, A, B, alpha, beta, gamma)
    new_A = update_A(X, mx, mz, w, A, B, alpha, beta, gamma)
    new_B = update_B(X, mx, mz, w, A, B, alpha, beta, gamma)
    
    return (new_w, new_A, new_B)

In [80]:
def calculate_alpha(X, mx, mz, w, A, B):
    n = X.shape[0]
    alpha = np.zeros((n, mz))
    for t in range(n):
        for i in range(mz):
            x = X[t] - 1
            if t == 0:
                alpha[t,i]=w[i] * B[i,x]
            else:
                alpha[t,i] = np.sum(alpha[t-1, :] * A[:, i] * B[i, X[t]-1])
    return alpha

alpha = calculate_alpha(X, mx, mz, w, A, B)


In [81]:
def calculate_beta(X, mx, mz, w, A, B):
    n = X.shape[0]
    beta = np.ones((n, mz))
    
    for t in reversed(range(n-1)):
        
        for i in range(mz):            
            beta[t,i] = np.sum( A[i, :] * B[:, X[t+1]-1 ] * beta[t+1, :] )

    
    return beta

beta = calculate_beta(X, mx, mz, w, A, B)


In [82]:
def calculate_gamma(X, mx, mz, w, A, B, alpha, beta):
    n = X.shape[0]
    gamma = np.zeros((n-1, mz, mz))
    
    for t in range(n-1):
        for i in range(mz):
            for j in range(mz):
                gamma[t, i, j] = alpha[t,i] * A[i,j] * B[j, X[t+1]-1] * beta[t+1, j]
    gamma = gamma/np.einsum('ijk->i', gamma)[:, np.newaxis, np.newaxis]
    return gamma

gamma = calculate_gamma(X, mx, mz, w, A, B, alpha, beta)


# print(gamma[0:2])
# print(np.einsum('ijk->i', gamma[0:2]))
# print(gamma[0:5] / np.einsum('ijk->i', gamma[0:5])[:, np.newaxis, np.newaxis])
#print(gamma / np.einsum('ijk->i', gamma))

#gamma[0].shape
#gamma.shape

In [83]:
def update_w(X, mx, mz, w, A, B, alpha, beta, gamma):
    updated_w = np.sum(gamma[0], axis=1)
    return updated_w

updated_w = update_w(X, mx, mz, w, A, B, alpha, beta, gamma)


In [84]:
def update_A(X, mx, mz, w, A, B, alpha, beta, gamma):
    updated_A = A
    updated_A = np.sum(gamma, axis=0) / np.sum(np.sum(gamma, axis=2), axis=0).reshape(-1,1)
    return updated_A

updated_A = update_A(X, mx, mz, w, A, B, alpha, beta, gamma)
updated_A

array([[0.485465  , 0.514535  ],
       [0.48503179, 0.51496821]])

In [85]:
def update_B(X, mx, mz, w, A, B, alpha, beta, gamma):
    n = X.shape[0]
    updated_B = np.zeros(B.shape)
    
    gamma_t = np.sum(gamma, axis=1)
    gamma_n = np.sum(gamma[n-2], axis=0)
    gamma_t = np.append(gamma_t, np.array([gamma_n]), axis=0)
    
    for i in range(mz):
        for l in range(mx):
            
            gamma_t_matched = gamma_t[X==(l+1)] 
            nr = np.sum(gamma_t_matched, axis = 0)[i]
            dr = np.sum(gamma_t, axis = 0)[i]
            
            updated_B[i,l] = nr / dr
    return updated_B

updated_B = update_B(X, mx, mz, w, A, B, alpha, beta, gamma)
updated_B

array([[0.28315801, 0.19032643, 0.52651556],
       [0.28673689, 0.1896922 , 0.52357092]])

In [86]:
def myBW(X, mx, mz, w, A, B, itmax):
    new_A = A
    new_B = B
    for i in range(itmax):
        (new_w, new_A, new_B) = BW_onstep(X, mx, mz, w, new_A, new_B)
        
    
    return (new_w, new_A, new_B)
    

In [87]:
(new_w, new_A, new_B) = myBW(X, mx, mz, w, A, B, itmax)
print(f"new_w" )
print(f"{new_w}" )
print(f"new_A" )
print(f"{new_A}" )
print(f"new_B:" )
print(f"{new_B}" )

new_w
[0.50000015 0.49999985]
new_A
[[0.48546086 0.51453914]
 [0.48502678 0.51497322]]
new_B:
[[0.28499999 0.19000006 0.52499995]
 [0.28500001 0.18999994 0.52500004]]


In [88]:
def calculate_delta(X, mx, mz, w, A, B):
    n = X.shape[0]
    delta = np.zeros((n, mz))
    for t in range(n):
        for i in range(mz):
            x = X[t] - 1
            if t == 0:
                #print(f"B[i, :]={B[i, :]}, x={x}")
                delta[t,i]=w[i] * B[i,x]
            else:
                delta[t,i] = np.max(delta[t-1, :] * A[:, i]) * B[i, X[t]-1]
                #delta[t,i] = np.sum(delta[t-1, :] * A[:, i] * B[i, X[t]-1])
    return delta

delta = calculate_delta(X, mx, mz, w, new_A_Viterbi, new_B_Viterbi)
delta


array([[1.01330635e-001, 8.93333250e-002],
       [2.90498210e-002, 2.43983058e-002],
       [8.32810434e-003, 6.99459167e-003],
       [2.38753009e-003, 2.00523402e-003],
       [6.84465481e-004, 5.74867504e-004],
       [1.96224959e-004, 1.64805028e-004],
       [5.62544579e-005, 4.72468820e-005],
       [6.20727742e-006, 9.65213764e-006],
       [2.49422585e-006, 2.55134053e-006],
       [7.15053395e-007, 6.74393462e-007],
       [2.04994009e-007, 1.78261795e-007],
       [5.87683999e-008, 4.93582866e-008],
       [1.68479305e-008, 1.41502063e-008],
       [1.85904873e-009, 2.89076725e-009],
       [2.87519239e-010, 5.44509805e-010],
       [1.40707736e-010, 1.43929769e-010],
       [4.03385861e-011, 3.80448214e-011],
       [1.15644070e-011, 1.00563521e-011],
       [1.16699932e-012, 1.03734453e-012],
       [3.34559448e-013, 2.80989122e-013],
       [9.59126732e-014, 8.05549448e-014],
       [2.74965808e-014, 2.30937735e-014],
       [3.03405119e-015, 4.71786223e-015],
       [1.2

In [89]:
def myViterbi(X, mx, mz, w, A, B):
    n = X.shape[0]
    Z = np.zeros(n)
    
    delta = calculate_delta(X, mx, mz, w, A, B)
    for t in reversed(range(n)):
        if t == n-1:
            index = np.argmax(delta[t])
            Z[t] = index + 1
        else:
            j = int(Z[t+1] - 1)
            #print(A[:, j])
            index = np.argmax(delta[t] * A[:, j])
            Z[t] = index + 1
            
    
    return Z


In [90]:
new_A_Viterbi = np.array([
    [0.49793938, 0.50206062],
    [0.44883431, 0.55116569]
])

new_B_Viterbi = np.array([
    [0.22159897, 0.20266127, 0.57573976],
    [0.34175148, 0.17866665, 0.47958186]
])

In [91]:
Z = myViterbi(X, mx, mz, w, new_A_Viterbi, new_B_Viterbi)
np.array_equal(Z, Z_test)

True