# Coding Assignment - 4

#### Authors:
+ Yogananth Mahalingam - ym24 - MCS-DS
+ Qi Zhou - qizhou8 - MCS-DS
+ Derek Zhang - derekz3 - MCS-DS

#### Contributions:
Yoga, Derek & Qi worked on it independently. Brainstormed together & created the final version.

## Part 2: HMM

In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from matplotlib.colors import LogNorm



In [2]:
itmax = 100

mx = 3
mz = 2
w = np.array([0.5, 0.5])
A = np.array([[0.5, 0.5], 
              [0.5, 0.5]])
B = np.array([[1/9, 3/9, 5/9], 
              [1/6, 2/6, 3/6]])

X = np.loadtxt("coding4_part2_data.txt").astype(int)
# print(f"X.shape={X.shape}")
# print(f"X={X}")

Z_test = np.genfromtxt("Coding4_part2_Z.txt").astype(int)
# print(f"Z_test.shape={Z_test.shape}")
# print(f"Z_test={Z_test}")

# print(f"A={A}")

# print(f"B={B}")

In [3]:
def BW_onstep(X, mx, mz, w, A, B):
    new_w = w
    new_A = A
    new_B = B
    
    alpha = calculate_alpha(X, mx, mz, w, new_A, new_B)
    beta = calculate_beta(X, mx, mz, w, new_A, new_B)
    gamma = calculate_gamma(X, mx, mz, w, A, B, alpha, beta)
    
    new_w = update_w(X, mx, mz, w, A, B, alpha, beta, gamma)
    new_A = update_A(X, mx, mz, w, A, B, alpha, beta, gamma)
    new_B = update_B(X, mx, mz, w, A, B, alpha, beta, gamma)
    
    return (new_w, new_A, new_B)

In [4]:
def calculate_alpha(X, mx, mz, w, A, B):
    n = X.shape[0]
    alpha = np.zeros((n, mz))
    for t in range(n):
        for i in range(mz):
            x = X[t] - 1
            if t == 0:
                #print(f"B[i, :]={B[i, :]}, x={x}")
                alpha[t,i]=w[i] * B[i,x]
            else:
                t_prev = t-1
                #print(f"alpha[t_prev]={alpha[t_prev]}")
                #print(f"alpha[t-1, :] * A[:, i] * B[i, X[t]-1]={alpha[t-1, :] * A[:, i] * B[i, X[t]-1]}")
#                 print(f"alpha[t-1, :] ={alpha[t-1, :] }")
#                 print(f"A[:, i] ={ A[:, i] }")
#                 print(f"B[i, X[t]-1]={B[i, X[t]-1]}")
#                 print(f"alpha[t-1, :] * A[:, i] ={alpha[t-1, :] * A[:, i] }")
#                 print(f"alpha[t-1, :] * A[:, i] * B[i, X[t]-1]={alpha[t-1, :] * A[:, i] * B[i, X[t]-1]}")
#                 print(f"alpha[t-1, :] * A[:, i] * B[i, X[t]-1]={alpha[t-1, :] * A[:, i] * B[i, X[t]-1]}")
#                 print(f"alpha[t-1, :] * A[:, i] * B[i, X[t]-1]={alpha[t-1, :] * A[:, i] * B[i, X[t]-1]}")
                alpha[t,i] = np.sum(alpha[t-1, :] * A[:, i] * B[i, X[t]-1])
        #print(t)
    return alpha

# print(w)
# print(A)
# print(B)
# print(B[0, :])
alpha = calculate_alpha(X, mx, mz, w, A, B)
#np.sum(alpha) #0.6999110052213837
#np.sum(beta[0:199]) #0.6999110052213837
#print(alpha)
#print(alpha)
    

In [5]:
def calculate_beta(X, mx, mz, w, A, B):
    n = X.shape[0]
    beta = np.ones((n, mz))
    
    #beta[n-1] = np.repeat(1,mz)
    for t in reversed(range(n-1)):
#         if t == 194 :
#             break
        
        for i in range(mz):
            t_next = t+1
            x = X[t_next]-1
            
#             print(f"t={t}, A[i, :]={A[i, :]}")
#             print(f"B[:, X[t+1]-1 ]={B[:, X[t+1]-1 ]}")
#             print(f"beta[t+1, :]={beta[t+1, :]}")
#             print(f"A[i, :] * B[:, X[t+1]-1 ]={A[i, :] * B[:, X[t+1]-1 ]}")
#             print(f"A[i, :] * B[:, X[t+1]-1 ] * beta[t+1, :]={A[i, :] * B[:, X[t+1]-1 ] * beta[t+1, :]}")
            
            beta[t,i] = np.sum( A[i, :] * B[:, X[t+1]-1 ] * beta[t+1, :] )

    
    return beta

#print(B)
beta = calculate_beta(X, mx, mz, w, A, B)
#print(beta)


[[2.16733876e-96 2.16733876e-96]
 [4.10653660e-96 4.10653660e-96]
 [7.78080619e-96 7.78080619e-96]
 [1.47425802e-95 1.47425802e-95]
 [2.79333098e-95 2.79333098e-95]
 [5.29262711e-95 5.29262711e-95]
 [1.00281356e-94 1.00281356e-94]
 [7.22025762e-94 7.22025762e-94]
 [1.36804881e-93 1.36804881e-93]
 [2.59209249e-93 2.59209249e-93]
 [4.91133313e-93 4.91133313e-93]
 [9.30568383e-93 9.30568383e-93]
 [1.76318220e-92 1.76318220e-92]
 [1.26949118e-91 1.26949118e-91]
 [9.14033652e-91 9.14033652e-91]
 [1.73185324e-90 1.73185324e-90]
 [3.28140613e-90 3.28140613e-90]
 [6.21740109e-90 6.21740109e-90]
 [1.86522033e-89 1.86522033e-89]
 [3.53410167e-89 3.53410167e-89]
 [6.69619264e-89 6.69619264e-89]
 [1.26875229e-88 1.26875229e-88]
 [9.13501649e-88 9.13501649e-88]
 [1.73084523e-87 1.73084523e-87]
 [1.24620857e-86 1.24620857e-86]
 [8.97270167e-86 8.97270167e-86]
 [6.46034520e-85 6.46034520e-85]
 [1.93810356e-84 1.93810356e-84]
 [5.81431068e-84 5.81431068e-84]
 [1.10165887e-83 1.10165887e-83]
 [2.087353

In [6]:
def calculate_gamma(X, mx, mz, w, A, B, alpha, beta):
    n = X.shape[0]
    gamma = np.zeros((n-1, mz, mz))
    
    for t in range(n-1):
        for i in range(mz):
            for j in range(mz):
                t_next = t+1
                x = X[t_next]-1

                gamma[t, i, j] = alpha[t,i] * A[i,j] * B[j, X[t+1]-1] * beta[t+1, j]
    return gamma

#print(B)
gamma = calculate_gamma(X, mx, mz, w, A, B, alpha, beta)
#print(gamma)
    

[[[1.90117435e-97 1.71105692e-97]
  [1.90117435e-97 1.71105692e-97]]

 [[2.00123616e-97 1.80111254e-97]
  [1.80111254e-97 1.62100129e-97]]

 [[2.00123616e-97 1.80111254e-97]
  [1.80111254e-97 1.62100129e-97]]

 [[2.00123616e-97 1.80111254e-97]
  [1.80111254e-97 1.62100129e-97]]

 [[2.00123616e-97 1.80111254e-97]
  [1.80111254e-97 1.62100129e-97]]

 [[2.00123616e-97 1.80111254e-97]
  [1.80111254e-97 1.62100129e-97]]

 [[1.52093948e-97 2.28140922e-97]
  [1.36884553e-97 2.05326830e-97]]

 [[1.52093948e-97 1.36884553e-97]
  [2.28140922e-97 2.05326830e-97]]

 [[2.00123616e-97 1.80111254e-97]
  [1.80111254e-97 1.62100129e-97]]

 [[2.00123616e-97 1.80111254e-97]
  [1.80111254e-97 1.62100129e-97]]

 [[2.00123616e-97 1.80111254e-97]
  [1.80111254e-97 1.62100129e-97]]

 [[2.00123616e-97 1.80111254e-97]
  [1.80111254e-97 1.62100129e-97]]

 [[1.52093948e-97 2.28140922e-97]
  [1.36884553e-97 2.05326830e-97]]

 [[1.15591401e-97 1.73387101e-97]
  [1.73387101e-97 2.60080651e-97]]

 [[1.52093948e-97 1.

In [15]:
def update_w(X, mx, mz, w, A, B, alpha, beta, gamma):
    updated_w = np.sum(gamma[0], axis=1)
    #updated_w = gamma
    #print(gamma[0])
    #print(np.sum(gamma[0], axis=1))
    return updated_w

#print(gamma[0:2])
updated_w = update_w(X, mx, mz, w, A, B, alpha, beta, gamma)
#print(f"updated_w={updated_w}")

In [16]:
def update_A(X, mx, mz, w, A, B, alpha, beta, gamma):
    updated_A = A
    updated_A = np.sum(gamma, axis=0) / np.sum(np.sum(gamma, axis=2), axis=0).reshape(-1,1)
    return updated_A

updated_A = update_A(X, mx, mz, w, A, B, alpha, beta, gamma)
#print(f"updated_A={updated_A}")

# print(f"updated_A={updated_A[0, 1]}")
# print(f"updated_A={updated_A.T}")
# print(f"updated_A={np.sum(updated_A, axis=0)}")
# print(f"gamma={gamma[0:2]}")
# print(f"gamma={np.sum(gamma[0:2], axis=0)}")
# print(f"gamma={np.sum(np.sum(gamma[0:2], axis=2), axis=0).T}")

# print(f"gamma={np.sum(gamma[0:2], axis=0) / np.sum(np.sum(gamma[0:2], axis=2), axis=0)}")

# print(f"gamma={np.sum(gamma, axis=0)}")
# print(f"gamma={np.sum(np.sum(gamma, axis=2), axis=0)}")
# print(gamma.shape)

In [17]:
def update_B(X, mx, mz, w, A, B, alpha, beta, gamma):
    n = X.shape[0]
    updated_B = np.zeros(B.shape)
    #gamma_t = np.zeros(n, mz)
    
    gamma_t = np.sum(gamma, axis=1)
    gamma_n = np.sum(gamma[n-2], axis=0)
    gamma_t = np.append(gamma_t, np.array([gamma_n]), axis=0)
    
    #print(np.sum(gamma_t, axis = 0))
    #print(f"updated_B={updated_B}")
    #print(f"gamma_t.shape={gamma_t.shape}")
    for i in range(mz):
        for l in range(mx):
            #print(X==l)
            #print(f"X==l.shape={(X==l).shape}")
            
            gamma_t_matched = gamma_t[X==(l+1)] 
            nr = np.sum(gamma_t_matched, axis = 0)[i]
            dr = np.sum(gamma_t, axis = 0)[i]
            
            updated_B[i,l] = nr / dr
#     print(gamma_t.shape)
#     print(gamma_t)
#     print(np.sum(gamma, axis=1).shape)
#     for i in range(mz):
#         for l in range(mx):
#             x = 1
    return updated_B

updated_B = update_B(X, mx, mz, w, A, B, alpha, beta, gamma)
#print(f"updated_B={updated_B}")

In [18]:
def myViterbi(X, mx, mz, w, A, B):
    #Z = np.repeat(1, 200)
    Z = np.array([1])
    return Z

In [19]:
def myBW(X, mx, mz, w, A, B, itmax):
    new_A = A
    new_B = B
    for i in range(itmax):
        (new_w, new_A, new_B) = BW_onstep(X, mx, mz, w, new_A, new_B)
    
    return (new_w, new_A, new_B)
    

In [20]:
(new_w, new_A, new_B) = myBW(X, mx, mz, w, A, B, itmax)
# print(f"new_w" )
# print(f"{new_w}" )
print(f"new_A" )
print(f"{new_A}" )
print(f"new_B:" )
print(f"{new_B}" )

new_A
[[0.48546086 0.51453914]
 [0.48502678 0.51497322]]
new_B:
[[0.28499999 0.19000006 0.52499995]
 [0.28500001 0.18999994 0.52500004]]


In [13]:
(new_w, new_A, new_B) = myBW(X, mx, mz, w, A, B, 10)
# print(f"new_w" )
# print(f"{new_w}" )
print(f"new_A" )
print(f"{new_A}" )
print(f"new_B:" )
print(f"{new_B}" )

new_A
[[0.48546092 0.51453908]
 [0.48502685 0.51497315]]
new_B:
[[0.28499999 0.19000006 0.52499995]
 [0.28500001 0.18999994 0.52500004]]


In [14]:
Z = myViterbi(X, mx, mz, w, new_A, new_B)
np.array_equal(Z, Z_test)

False